/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.macro.mall;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.runtime.SmartAssertions.*;
import com.macro.mall.MallAdminApplication;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class MallAdminApplication_SSTest extends MallAdminApplication_SSTest_scaffolding {
// allCoveredLines:[11, 13]

  @Test(timeout = 4000)
  public void test_main_0()  throws Throwable  {
      //caseID:2f22fa9050d98d69e28fb1d350d7f9ad
      //CoveredLines: [11, 13]
      //Input_0_String[]: stringArray0
      
      MallAdminApplication mallAdminApplication0 = new MallAdminApplication();
      String[] stringArray0 = new String[0];
      
      //Call method: main
      // Undeclared exception!
      try { 
        MallAdminApplication.main(stringArray0);
      } catch(Throwable e) {
         verifyException("org.springframework.core.io.support.SpringFactoriesLoader", e);
         assertEquals("org.smartunit.runtime.mock.java.lang.MockIllegalArgumentException", e.getClass().getName());
         assertEquals("Unable to instantiate factory class [org.springframework.boot.logging.log4j2.Log4J2LoggingSystem.Factory] for factory type [org.springframework.boot.logging.LoggingSystemFactory]", e.getMessage());
      }
  }
}
